// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IVerifier
/// @notice Interface for the Groth16 verifier contract generated by snarkjs.
/// @dev Signature MUST match `Groth16Verifier.verifyProof` exactly:
///      - _pA:         pi_a            (uint[2])
///      - _pB:         pi_b            (uint[2][2])
///      - _pC:         pi_c            (uint[2])
///      - _pubSignals: public inputs   (uint[3] = [commitment_A, commitment_B, clearingPrice])
///      nPublic = 3, so _pubSignals has fixed length 3.
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[3] calldata _pubSignals
    ) external view returns (bool);
}
