// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {Groth16Verifier} from "../src/Verifier.sol";
import {OrderBook} from "../src/OrderBook.sol";
import {DarkPoolSettlement} from "../src/DarkPoolSettlement.sol";

/// @title Deploy
/// @notice Deploys the ShadowPool v1 contract stack to Sepolia and writes the
///         resulting addresses to shared/addresses.json for the prover, watcher,
///         and frontend.
///
/// @dev Two-step wiring resolves the OrderBook<->Settlement construction cycle:
///        1. deploy Verifier
///        2. deploy OrderBook with settlement = address(0)
///        3. deploy DarkPoolSettlement(verifier, orderBook)
///        4. orderBook.setSettlement(settlement)  (one-time)
contract Deploy is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("DEPLOYER_PRIVATE_KEY");
        vm.startBroadcast(deployerKey);

        // 1. Verifier (generated by snarkjs from the real zkey)
        Groth16Verifier verifier = new Groth16Verifier();
        console.log("Verifier deployed:", address(verifier));

        // 2. OrderBook with placeholder settlement
        OrderBook orderBook = new OrderBook(address(0));
        console.log("OrderBook deployed:", address(orderBook));

        // 3. Settlement with real addresses
        DarkPoolSettlement settlement =
            new DarkPoolSettlement(address(verifier), address(orderBook));
        console.log("Settlement deployed:", address(settlement));

        // 4. Wire settlement into OrderBook (one-time)
        orderBook.setSettlement(address(settlement));
        console.log("OrderBook.settlement wired");

        vm.stopBroadcast();

        // Persist addresses for prover / watcher / frontend.
        string memory json = string(
            abi.encodePacked(
                '{"verifier":"',
                vm.toString(address(verifier)),
                '","orderBook":"',
                vm.toString(address(orderBook)),
                '","settlement":"',
                vm.toString(address(settlement)),
                '","network":"sepolia","chainId":11155111}'
            )
        );
        vm.writeFile("../shared/addresses.json", json);
        console.log("Wrote ../shared/addresses.json");
    }
}
